version: '3.8'
services:
  isnadcore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443" 
    depends_on:
      - neo4j
    networks:
      - isnadcore_network

  neo4j:
    image: neo4j:latest 
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
    networks:
      - isnadcore_network

networks:
  isnadcore_network:

volumes:
  neo4j_data:
